name: First Workflow 

on: 
  push:
    branches:
      - main
jobs:
  examble-jop:
    runs-on: ubuntu-latest
    steps:
      - name: print a welcome message 
        run: echo "welcome to my first git hub action lap" 
      - name: checkout repo
        uses: actions/checkout@v6.0.2
      - name: list repo files
        run: ls -la
        
